// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "shark1":return img`
.............ccfff..............
...........ccddbcf..............
..........ccddbbf...............
..........fccbbcf...............
.....fffffccccccff.........ccc..
...ffbbbbbbbcbbbbcfff....ccbbc..
..fbbbbbbbbcbcbbbbcccff.cdbbc...
ffbbbbbbffbbcbcbbbcccccfcdbbf...
fbcbbb11ff1bcbbbbbcccccffbbf....
fbbb11111111bbbbbcccccccbbcf....
.fb11133cc11bbbbcccccccccccf....
..fccc31c111bbbcccccbdbffbbcf...
...fc13c111cbbbfcddddcc..fbbf...
....fccc111fbdbbccdcc.....fbbf..
........ccccfcdbbcc........fff..
.............fffff..............
`;
            case "image2":
            case "heart":return img`
....................
....................
....................
....2222...2222.....
...222222.222222....
..222222222222222...
..222222222222222...
..222222222222222...
..222222222222222...
..222222222222222...
..222222222222222...
...2222222222222....
....22222222222.....
.....222222222......
......2222222.......
.......22222........
........222.........
.........2..........
.........2..........
....................
`;
            case "image3":
            case "obstacle":return img`
....................
....................
....................
....ffff...ffff.....
...ffffff.ffffff....
..fffffffffffffff...
..fffffffffffffff...
..fffffffffffffff...
..fffffffffffffff...
..fffffffffffffff...
..fffffffffffffff...
...fffffffffffff....
....fffffffffff.....
.....fffffffff......
......fffffff.......
.......fffff........
........fff.........
.........f..........
.........f..........
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
